### ISSUE TITLE
Control consultas

### ISSUE THREAD

**Issue by Ardrein** [Ardrein/libreria#2]
Falta realizar el control de los Daos a través de los EJB y los delegate.

**Comment by santiagoRueda** [comment]
Los delegados salen en un momentico, ya teniendo estas consultas y los daos, seria terminar esos EJB que no requieren de mucho tampoco y mandarselo a alvarez. Creeria que vicctor se untara un poco jajajaj

**Comment by Ardrein** [comment]
Finalizado el control (EJBLibro) para la consulta de datos de los libros (primer y segundo punto de la entrega).
Finalizado el control (EJBLibro) para obtener la suma de los puntajes de un libro y la cantidad de veces que se ha calificado.

Falta realizar la inserción de puntuación y de comentarios en los EJB de DetallesLibro.

**Comment by Ardrein** [comment]
Finalizado el control(EJBDetallesLibro) para la inserción de puntuación y de comentarios en los EJB de detallesLibro.
Finalizados los delegate para calificar, puntuar y demás controles realizados anteriormente

**Comment by Ardrein** [comment]
Finalizado el control de las consultas.
